"""common_name (not family_name + given_name)

Revision ID: 0002
Revises: 0001
Create Date: 2024-02-26 16:57:59.745305

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel                 # CHANGED!


# revision identifiers, used by Alembic.
revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('common_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('person', 'family_name')
    op.drop_column('person', 'given_names')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('given_names', sa.VARCHAR(), nullable=False))
    op.add_column('person', sa.Column('family_name', sa.VARCHAR(), nullable=False))
    op.drop_column('person', 'common_name')
    # ### end Alembic commands ###
